import { http, HttpResponse } from 'msw'
// Real backend responses (generated by the backend's TestClient on synthetic data): numbers, never formatted strings
import real from './fixtures/backend-real.json'
import { candidate } from './fixtures/candidate'

// the client resolves '/api' against the jsdom origin (http://localhost:3000)
const u = (path: string) => `*/api${path}`

export const scanSignal = {
  symbol: 'AAPL',
  pattern: 'golden_cross',
  signal: 'BUY',
  signal_date: '2026-01-02T00:00:00',
  days_ago: 2,
  price: 190.5,
  win_rate: 0.6,
  profit_factor: 1.8,
  sharpe: 1.2,
  total_return: 0.153, // backend sends a fraction
  total_trades: 12,
  is_valid: true,
}

const dates = ['2026-01-01T00:00:00', '2026-01-02T00:00:00', '2026-01-05T00:00:00']

export const pairAnalysis = {
  symbol_a: 'KO',
  symbol_b: 'PEP',
  is_cointegrated: true,
  is_valid: true,
  coint_pvalue: 0.012,
  hedge_ratio: 0.9,
  half_life: 12.3,
  correlation: 0.88,
  current_zscore: 1.1,
  spread_data: dates.map((date, i) => ({ date, spread: i, zscore: i - 1 })),
  prices_a: dates.map((date, i) => ({ date, price: 60 + i })),
  prices_b: dates.map((date, i) => ({ date, price: 170 + i })),
  backtest: {
    total_return: 0.08, max_drawdown: -0.12, total_trades: 5, win_rate: 0.6,
    oos: true, oos_status: 'ok', oos_blocks: 3, oos_blocks_tradable: 2, latest_block_tradable: false, oos_significant: false,
    psr: 0.71, exit_reasons: { exit: 3, coint_break: 1, time_stop: 1 },
    blocks: [
      { block: 0, trade_start: '2025-01-02T00:00:00', trade_end: '2025-04-01T00:00:00', tradable: true, coint_pvalue: 0.012, half_life: 12.3, n_trades: 3, n_breaks: 0 },
      { block: 1, trade_start: '2025-04-02T00:00:00', trade_end: '2025-07-01T00:00:00', tradable: true, coint_pvalue: 0.03, half_life: 15.1, n_trades: 2, n_breaks: 1 },
      { block: 2, trade_start: '2025-07-02T00:00:00', trade_end: '2025-09-30T00:00:00', tradable: false, untradable_reason: 'not_cointegrated', coint_pvalue: 0.26, half_life: null, n_trades: 0, n_breaks: 0 },
    ],
  },
}

// Phase 2 convention: ratios are fractions, non-finite -> null
export const metrics = {
  symbol: 'AAPL',
  pattern: 'golden_cross',
  total_trades: 12,
  win_rate: 0.6,
  avg_win: 0.03,
  avg_loss: -0.01,
  profit_factor: 1.8,
  total_return: 0.153,
  max_drawdown: -0.08,
  sharpe: 1.2,
  sortino: 1.5,
  calmar: 1.1,
  expectancy: 0.01,
  avg_duration_days: 8.0,
  valid: true,
}

const equity = dates.map((date, i) => ({ date, value: 100000 + i * 100 }))

export const nightly = {
  kind: 'technical',
  payload: [scanSignal],
  generated_at: '2026-01-02T22:30:00+00:00',
  age_hours: 3.5,
  stale: false,
}

// ---- Overview page fixtures (portfolio overview, risk status, allocation proposal, scan funnel) ----
const ovDates = Array.from({ length: 30 }, (_, i) => `2026-09-${String(i + 1).padStart(2, '0')}`)
// Invented numbers only: a CAD margin account, net 100,000 on 157,000 of holdings (1.57x).
export const accountFixture = {
  available: true, source: 'ibkr', as_of: '2026-09-30T20:05:00+00:00', age_hours: 3.5, base_currency: 'CAD',
  net_worth: 100000, positions_value: 157000, cash: -57000, margin_loan: 57000, leverage: 1.57,
  max_leverage_warn: 1.0, margin_headroom: 31000, maint_margin: 52000, buying_power: 62000, positions: 13,
  warnings: ['Leverage 1.57x is above the 1.00x warning level (margin loan 57,000 CAD). Reduce the margin loan before adding new positions.'],
  note: null,
}
export const overviewFixture = {
  as_of: '2026-09-30',
  range: '1Y',
  base_currency: 'CAD',
  source: 'ibkr',
  total_value: 100000,
  net_worth: 100000,
  positions_value: 157000,
  margin_loan: 57000,
  leverage: 1.57,
  margin_headroom: 31000,
  account: accountFixture,
  day_change: 612.4,
  day_change_pct: 0.0049,
  cash: -57000,
  accounts: [
    { key: 'core', label: 'Core portfolio', value: 130000, share: 1.3 },
    { key: 'trend', label: 'Trend sleeve', value: 27000, share: 0.27 },
    { key: 'cash', label: 'Cash', value: -57000, share: -0.57 },
  ],
  paper_sleeve: { label: 'Alpaca paper', value: 9860, peak: 10000, drawdown: -0.014, as_of: '2026-09-30', note: '' },
  period_return: 0.152,
  benchmark_return: 0.125,
  max_drawdown: -0.061,
  series: ovDates.map((date, i) => ({
    date,
    portfolio: 100 + i * 0.5,
    benchmark: 100 + i * 0.4,
    drawdown: i === 10 ? -0.061 : 0,
  })),
  method: 'fixture',
  benchmark_label: '60/40 benchmark',
  allocation: [
    { key: 'us_equity', label: 'US equity', target: 0.356, now: 0.379, drift: 0.023 },
    { key: 'intl_equity', label: 'International equity', target: 0.256, now: 0.224, drift: -0.032 },
    { key: 'treasuries', label: 'Treasuries', target: 0.224, now: 0.213, drift: -0.011 },
    { key: 'gold', label: 'Gold & miners', target: 0.1, now: 0.1, drift: 0 },
    { key: 'thematic', label: 'Thematic & single names', target: 0.04, now: 0.04, drift: 0 },
    { key: 'other', label: 'Other', target: 0.02, now: 0.044, drift: 0.024 },
  ],
  allocation_basis: 'Shares of invested value; cash excluded.',
  unpriced: [],
  warnings: [accountFixture.warnings[0], 'The benchmark (SPY/IEF) is in US dollars and is not converted to CAD.'],
}

/** The same account with no borrowing, from holdings.csv. */
export const unleveredOverviewFixture = {
  ...overviewFixture,
  source: 'holdings_csv', base_currency: 'USD', total_value: 124380.52, net_worth: 124380.52, positions_value: 119820.52,
  margin_loan: 0, leverage: 0.96, margin_headroom: null, cash: 4560,
  account: { ...accountFixture, source: 'holdings_csv', as_of: null, base_currency: 'USD', net_worth: 124380.52,
    positions_value: 119820.52, cash: 4560, margin_loan: 0, leverage: 0.96, margin_headroom: null, maint_margin: null, warnings: [] },
  accounts: [
    { key: 'core', label: 'Core portfolio', value: 107940, share: 0.868 },
    { key: 'trend', label: 'Trend sleeve', value: 11880, share: 0.096 },
    { key: 'cash', label: 'Cash', value: 4560, share: 0.037 },
  ],
  warnings: [],
}

export const riskFixture = {
  mode: 'paper', paper_trade_enabled: true, halted: false, halt_reason: null, halted_at: null, kill_switch: false,
  reconcile: { broker_checked: false, status: 'clean', mismatches: [], note: '' },
  sleeve_value: 9860, sleeve_as_of: '2026-09-30', configured_equity: 10000, peak: 10000, drawdown: -0.014,
  ladder: [
    { kind: 'cut', drawdown: 0.05, risk_multiplier: 0.5, label: 'cut', threshold_equity: 9500, room: 360 },
    { kind: 'cut', drawdown: 0.08, risk_multiplier: 0.25, label: 'cut', threshold_equity: 9200, room: 660 },
    { kind: 'halt', drawdown: 0.1, risk_multiplier: 0, label: 'halt', threshold_equity: 9000, room: 860 },
  ],
  open_positions: 2, max_positions: 8,
  limits: [
    { key: 'heat', label: 'Open risk to stops', used: 0.012, maximum: 0.04, unit: 'fraction' },
    { key: 'positions', label: 'Positions', used: 2, maximum: 8, unit: 'count' },
    { key: 'orders_today', label: 'Orders today', used: 1, maximum: 5, unit: 'count' },
  ],
  account: accountFixture,
  equity_history: [], decision_window_days: 30, decision_total: 0, decision_reasons: [], decisions: [],
}

export const funnelFixture = { tested: 780, min_trades: 312, oos_positive: 41, psr: 3, bh: 0, dsr: 0, orders: 0, n_trials: 780, pbo: 0.55, sharpe_var: 0.0004, run_id: 'tech-20261002T223000000000' }

export const proposalFixture = {
  advisory: 'Proposals only.', as_of: '2026-09-30', cash: 4560, cash_after: 100, contribution: 0, groups: [],
  groups_basis: '', notes: [], rows: [], signal_month: null, total_value: 124380.52, trend: [], unmanaged: [],
  trades: [
    { symbol: 'VEA', action: 'buy', shares: 41, amount: 2000 },
    { symbol: 'PDBC', action: 'buy', shares: 108, amount: 1800 },
    { symbol: 'TLT', action: 'buy', shares: 11, amount: 1000 },
  ],
}

export const briefingFixture = {
  status: 'ok',
  generated_at: '2026-10-05T22:40:00+00:00',
  model: 'claude-opus-5-5',
  reason: null,
  error: null,
  briefing: {
    headline: 'Scan found no new survivors; the signal sleeve is quiet',
    observations: ['780 candidates tested, none cleared deflated Sharpe', 'International equity is 3 points under target'],
    risks: ['Drawdown is 1.4% from peak; the halt is at 10%'],
    what_changed: ['One fewer candidate passed the hold-out gate than last night'],
  },
  usage: { input_tokens: 4200, output_tokens: 310, cache_creation_input_tokens: 0, cache_read_input_tokens: 0 },
  cost_usd: 0.012,
  cost_estimated: false,
  request_id: 'req_test',
  budget: { spent_today_usd: 0.012, daily_limit_usd: 0.5, spent_month_usd: 0.41, monthly_limit_usd: 5 },
  advisory: 'Advisory only: nothing here is an instruction to trade. Nothing is ordered.',
}

const overviewHandlers = [
  http.get(u('/briefing'), () => HttpResponse.json(briefingFixture)),
  http.get(u('/portfolio/overview'), () => HttpResponse.json(overviewFixture)),
  http.get(u('/risk/status'), () => HttpResponse.json(riskFixture)),
  http.get(u('/allocation/proposal'), () => HttpResponse.json(proposalFixture)),
]

export const handlers = [
  http.get(u('/scanner/candidate'), () => HttpResponse.json(candidate)),
  // no nightly run stored by default; tests opt in with server.use(...)
  http.get(u('/results/technical/latest'), () =>
    HttpResponse.json({ error: { code: 'not_found', message: "No stored result for 'technical'" } }, { status: 404 })),
  http.get(u('/data/watchlist/symbols'), () =>
    HttpResponse.json({ us_stocks: ['AAPL', 'MSFT'], crypto: ['BTC-USD'] })),
  http.get(u('/data/:symbol'), ({ params }) =>
    HttpResponse.json({
      symbol: params.symbol,
      count: 3,
      data: dates.map((date, i) => ({
        date, open: 100 + i, high: 102 + i, low: 99 + i, close: 101 + i, volume: 1000000,
      })),
    })),
  http.get(u('/patterns/list'), () =>
    HttpResponse.json({ patterns: ['golden_cross', 'rsi_reversal'], count: 2 })),
  http.post(u('/patterns/detect'), async ({ request }) => {
    const body = (await request.json()) as { symbol: string; pattern_name: string }
    return HttpResponse.json({
      symbol: body.symbol,
      pattern: body.pattern_name,
      total_signals: 2,
      buys: [{ date: dates[0], price: 101 }],
      sells: [{ date: dates[2], price: 103 }],
      latest_signal: { date: dates[2], signal: 'SELL', price: 103 },
    })
  }),
  http.post(u('/patterns/scan'), () =>
    HttpResponse.json({ count: 1, signals: [scanSignal] })),
  http.post(u('/backtest/run'), () =>
    HttpResponse.json({
      symbol: 'AAPL',
      pattern: 'golden_cross',
      metrics: real.backtest_metrics,
      equity_curve: equity,
      trades: [{
        entry_date: dates[0], exit_date: dates[2], direction: 'LONG',
        entry_price: 101, exit_price: 103, pnl_pct: 0.0198, exit_reason: 'signal', bars_held: 2,
      }],
      is_valid: true,
    })),
  http.post(u('/backtest/walk-forward'), () =>
    HttpResponse.json({
      symbol: 'AAPL', pattern: 'golden_cross', n_folds: 1,
      folds: [{ fold: 1, metrics }],
    })),
  http.get(u('/pairs/configured'), () =>
    HttpResponse.json({ pairs: [{ a: 'KO', b: 'PEP' }] })),
  http.post(u('/pairs/analyze'), () => HttpResponse.json(pairAnalysis)),
  http.post(u('/pairs/scan'), () =>
    HttpResponse.json({ count: 1, pairs: [{ symbol_a: 'KO', symbol_b: 'PEP', is_valid: true }] })),
  http.post(u('/ml/predict'), () =>
    HttpResponse.json({
      symbol: 'AAPL',
      model_type: 'ensemble_rf_xgb_lgbm',
      feature_importance: [{ feature: 'rsi_14', importance: 0.12 }],
      signals: real.ml_signals,
      total_signals: real.ml_signals.length,
      metrics: real.ml_metrics,
      equity_curve: equity,
      is_valid: true,
      n_oos_bars: 300,
      calibrated: true,
      model_selected: 'logreg',
      abstain_reasons: { band: 41, drift: 7 },
      last_abstain_reason: 'drift',
    })),
  http.post(u('/stress/full'), () =>
    HttpResponse.json({
      symbol: 'AAPL',
      pattern: 'golden_cross',
      monte_carlo: {
        n_simulations: 1000, return_mean: 0.1, return_5th_pct: -0.05, return_95th_pct: 0.3,
        prob_positive: 0.7, drawdown_mean: -0.1, sharpe_mean: 1.0, sharpe_ci_low: 0.2, sharpe_ci_high: 1.8,
      },
      regimes: real.stress_regimes,
      sensitivity: [],
      assessment: {
        regimes_consistent: true, mc_prob_positive: 0.7, mc_worst_case_5pct: -0.05, param_robust: true,
      },
    })),
  http.get(u('/config/'), () =>
    HttpResponse.json({
      watchlist: { us_stocks: ['AAPL'] },
      pairs: [{ a: 'KO', b: 'PEP' }],
      backtest: { lookback_days: 730, initial_capital: 100000, commission_pct: 0.001 },
      validation: { min_win_rate: 0.5, min_trades: 10 },
      risk: { max_position_pct: 0.1 },
      ml: { n_estimators: 100 },
    })),
  ...overviewHandlers,
]

// ---- Allocation page fixtures (GET /api/allocation/proposal) ----
const alRow = (symbol: string, name: string, group: string, target: number, current: number,
  price: number, trade_shares: number) => {
  const value = Math.round(current * 124380)
  return {
    symbol, name, group, price, shares: Math.round(value / price), value, target, current, drift: current - target,
    band: Math.max(0.05, 0.25 * target), outside: Math.abs(current - target) > Math.max(0.05, 0.25 * target),
    action: trade_shares > 0 ? 'buy' : trade_shares < 0 ? 'sell' : 'hold', trade_shares, trade_value: trade_shares * price,
  }
}
const alMonths = (slope: number) => {
  let v = 100
  const closes = Array.from({ length: 22 }, (_, i) => (v *= 1 + slope + Math.sin(i) * 0.02))
  return closes.slice(9).map((close, i) => ({
    month: `${i < 4 ? 2025 : 2026}-${String(((i + 8) % 12) + 1).padStart(2, '0')}`,
    close, average: i >= 3 ? close * 0.97 : null,
  }))
}
const alTrend = (symbol: string, name: string, state: string, votes: boolean[], slope: number) => ({
  symbol, name, state, score: votes.filter(Boolean).length / 3, weight: state === 'held' ? 0.0167 : state === 'tbills' ? 0 : 0.0111,
  data_available: true, months: alMonths(slope),
  votes: [8, 10, 12].map((lookback, i) => ({ lookback, above: votes[i], average: 100 })),
})

export const allocationFixture = {
  advisory: 'Advisory only: nothing is ordered. Place any trades yourself in IBKR (D1).',
  as_of: '2026-09-30', signal_month: '2026-08', total_value: 124380, cash: 4560, contribution: 0, cash_after: 150,
  groups_basis: 'Share of invested value (cash excluded).',
  notes: [], unmanaged: [],
  rows: [
    alRow('VTI', 'US total market', 'us_equity', 0.32, 0.336, 280, 0),
    alRow('VEA', 'Developed ex-US', 'intl_equity', 0.18, 0.125, 51.5, 41),
    alRow('VWO', 'Emerging', 'intl_equity', 0.05, 0.047, 48, 0),
    alRow('IEF', 'Treasuries 7-10y', 'treasuries', 0.13, 0.124, 95, 0),
    alRow('TLT', 'Treasuries 20y+', 'treasuries', 0.07, 0.062, 89.5, 11),
    alRow('TIP', 'TIPS', 'tips_bills', 0.07, 0.073, 108, 0),
    alRow('SGOV', 'T-bills', 'tips_bills', 0.08, 0.099, 100.5, 0),
    alRow('GLDM', 'Gold', 'gold_commodities', 0.05, 0.061, 62, 0),
    alRow('PDBC', 'Commodities', 'gold_commodities', 0.05, 0.037, 14, 108),
  ],
  trades: [
    { symbol: 'VEA', action: 'buy', shares: 41, amount: 2111.5 },
    { symbol: 'PDBC', action: 'buy', shares: 108, amount: 1512 },
    { symbol: 'TLT', action: 'buy', shares: 11, amount: 984.5 },
  ],
  groups: [
    { key: 'us_equity', label: 'US equity', target: 0.32, now: 0.348, after: 0.335, drift: 0.028 },
    { key: 'intl_equity', label: 'International equity', target: 0.23, now: 0.178, after: 0.22, drift: -0.052 },
    { key: 'treasuries', label: 'Treasuries', target: 0.2, now: 0.19, after: 0.198, drift: -0.01 },
    { key: 'tips_bills', label: 'TIPS & T-bills', target: 0.15, now: 0.176, after: 0.16, drift: 0.026 },
    { key: 'gold_commodities', label: 'Gold & commodities', target: 0.1, now: 0.108, after: 0.087, drift: 0.008 },
  ],
  trend: [
    alTrend('SPY', 'S&P 500', 'held', [true, true, true], 0.012),
    alTrend('VEA', 'Developed ex-US', 'partial', [true, true, false], 0.004),
    alTrend('IEF', 'Treasuries 7-10y', 'tbills', [false, false, false], -0.008),
    alTrend('GLD', 'Gold', 'held', [true, true, true], 0.016),
    alTrend('DBC', 'Commodities', 'partial', [false, true, false], -0.001),
    alTrend('VNQ', 'US real estate', 'tbills', [false, false, false], -0.006),
  ],
}

// ---- Risk page fixtures (risk worker) ----
const riskDay = (i: number) => `2026-09-${String(i + 1).padStart(2, '0')}T21:00:00+00:00`
const riskEquity = [10000, 10040, 10080, 10020, 9960, 9900, 9860]
export const riskPageFixture = {
  ...riskFixture,
  equity_history: riskEquity.map((v, i) => ({ ts: riskDay(i), sleeve_equity: v, peak: Math.max(...riskEquity.slice(0, i + 1)) })),
  peak: 10080, drawdown: -0.0218, sleeve_value: 9860,
  decision_total: 214,
  decision_reasons: [
    { reason: 'not_validated', count: 168 }, { reason: 'not_executable', count: 24 },
    { reason: 'shorts_disabled', count: 15 }, { reason: 'duplicate', count: 7 },
  ],
  decisions: [
    { ts: '2026-09-28T21:42:00+00:00', symbol: 'QQQ', side: 'buy', status: 'rejected', reasons: ['not_validated'], source: 'ledger' },
    { ts: '2026-09-28T21:42:00+00:00', symbol: 'MSFT', side: 'sell', status: 'rejected', reasons: ['shorts_disabled'], source: 'ledger' },
    { ts: '2026-09-25T21:40:00+00:00', symbol: 'XOM', side: 'buy', status: 'dry_run', reasons: ['TRADING_MODE=off'], source: 'scan_run' },
  ],
}
